### PR TITLE
Add a Dart demo script

### LINKED ISSUE #86: Dart support
This visualizer would go great with Flutter!

### PR DESCRIPTION
**Pull request by DanTup**
I created a small demo script in Dart that renders charts, graphs and trees:

viz

Feel free to tweak, or let me know if there's anything I can do to improve it.

Thanks!

(Fixes #86?)

### CODE REVIEW

**Comment by hediet** [comment]
Thank you for the dart demo!

It would be awesome to fully support dart by adding data extractors! They make it possible to visualize non-json values!
[Here](https://github.com/hediet/rider-plugin-debug-visualizer-dotnet-sdk/blob/826b5a836317aa7b0f161281693cd2697f9fbcab/DebugVisualizer.Brokerage/VisualizationBrokerService.cs#L28) is an example of how data extractors are implemented in C#. Rather than `myValue`, `global::DebugVisualizer.Brokerage.VisualizationBrokerService.BrokerJson(myValue, "{ \"preferreBrokerId\": \"myPreferredBroker\" }")` is visualized. This requires a runtime though. In case of typescript, the runtime is just injected into the debuggee through `eval`.

What are your ideas on this?

**Review by Zuraki — APPROVED** [review]

**Comment by DanTup** [comment]
Sorry for the delay in repsonding. I don't think there's an easy way to inject anything like that in Dart (I don't believe we can just `eval` to create new functions). I also suspect most people would have their own data structures and would need to map them onto the structure for this extension anyway, so having them include the JSON (and/or copy it from this demo) is probably not much more effort (and may also be more flexible).

**Comment by Zuraki** [comment]
Do you have any app for facetime? Because i'm always figure it out that my
partner is been hiding something. Do you have any suggestions that i can
use her camera on her phone that she will not going to know that i'm using
her phone as a camera

**Comment by Zuraki** [comment]
How can i do this?

**Pull request merged**
