### PR TITLE
Add Nim demo

### PR DESCRIPTION
**Pull request by Yardanico**
Hello! Thanks for this cool extension, I really liked it and decided to create a Nim demo.
If there are any issues with it - please tell me.

And I have a question - what is the license used for the demos? Does GPLv3 apply to them as well? If so, please do not merge this PR, as I maybe would expand this demo into a Nim library to be used with this extension.

### CODE REVIEW

**Comment by hediet** [comment]
Hey there, thank you very much for your PR! Do you have an idea how I would best license the demos? Can you add a LICENSE file to your demo folder?

**Comment by Yardanico** [comment]
@hediet ah, yeah, if that's ok with you, I can do that.

**Comment by hediet** [comment]
As of my understanding, I think you don't loose anything if this GPL license would apply to your demo, unless somebody adds non-trivial changes to it through this repository and you want to integrate these changes back into your MIT licensed library.

As the sole owner, you can publish your work (i.e. free of any contributions) under as many licenses as you want. As MIT is strictly more permissive than GPLv3, consumers would always choose your MIT release.

**Comment by hediet** [comment]
Btw. it would be super awesome if you'd publish a nim library for this extension! Reach out to me if you have questions or ideas for improvements!

**Pull request merged**
